#!/bin/sh
# Cron wrapper for updating the Guardian CC data.

set -e

GUARDIAN_REPO="$HOME/guardian-cc"
XTEDDY_REPO="$HOME/website.deploy"

{
  cd "$GUARDIAN_REPO" && {
    git pull --quiet && {
	go build -o ~/bin/guardian-cc cmd/guardian-cc/main.go
    } || {
	echo "Couldn't rebuild go program" >&2
        exit 1
    }
  }
}

(
  cd "$GUARDIAN_REPO" && {
    git pull --quiet &&
      ./tools/web-scraper.py &&
      guardian-cc render
  }
)
(
  cd "$XTEDDY_REPO" && {
    git pull --quiet &&
      cp "$GUARDIAN_REPO/gcc-analysis.html" . &&
      cp "$GUARDIAN_REPO/ui/gcc.css" . &&
      cp "$GUARDIAN_REPO/ds_ajax.txt" . &&
      cp "$GUARDIAN_REPO/ds_ajax5a.txt" . &&
      cp "$GUARDIAN_REPO/ds_ajax2.txt" . &&
      git add gcc-analysis.html gcc.css ds_ajax.txt ds_ajax5a.txt ds_ajax2.txt &&
      git commit -m "Guardian CC update" &&
      git push
  }

  cd "$GUARDIAN_REPO" && {
    git add .
    git commit -am "Sync" && git push
  }
)
